version: "3.8"

services:
  web:
    image: yourdockerhub/next-portfolio:latest
    container_name: next-portfolio
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
